Stat svc
DenisLeonenko93/java-explore-with-me pull request #3
Opened 2023-08-04 10:02 UTC by DenisLeonenko93

2023-08-04 10:19 UTC, DenisLeonenko93 commented
Если честно, не совсем понял насчет тестов, их сейчас тоже надо сдавать, или это вообще по желанию. В любом случае тесты буду писать (пишу параллельно сейчас).

2023-08-05 09:06 UTC, z8q requested changes

2023-08-05 09:06 UTC, z8q commented on docker-compose.yml
> +#  ewm-service:
Если раскомментировать, тесты падают?

2023-08-05 11:52 UTC, DenisLeonenko93 commented on ewm-stats-service/stats_shared_dto/pom.xml
> +            <version>2.13.4.1</version>
Почему-то твое короткое объяснение мне помогло больше, чем урок на практикуме) Спасибо!

2023-08-05 11:54 UTC, DenisLeonenko93 commented on ewm-stats-service/stats_server/pom.xml
> +        <!--        <dependency>-->
Это я отметил для себя, что потом не искать какие зависимости нужны для тестов. Понял, к итоговой версиипроекта все комменты уберу

2023-08-05 11:57 UTC, DenisLeonenko93 commented on ewm-stats-service/stats_client/src/main/java/ru/practicum/StatClient.java
> +            return ResponseEntity.status(e.getStatusCode()).body(e.getResponseBodyAsByteArray());
Если я правильно понял, то когда напишу главный сервис, то клиент должен будет возвращать не ResponseEntity, а List<ViewResponseDto>. Когда буду писать мэйн-сервис учту, что от сервера статистики может прийти код не 200-й, в этом случае кину исключение. Спасибо за совет.

2023-08-05 12:05 UTC, DenisLeonenko93 commented on docker-compose.yml
> +#  ewm-service:
Да, тесты гита падают (возможно нужно правильно настроить). Займусь уже в мэйн сервисе.

2023-08-06 12:25 UTC, z8q approved these changes

2023-08-07 06:11 UTC, merged