Main svc
DenisLeonenko93/java-explore-with-me pull request #4
Opened 2023-08-17 18:50 UTC by DenisLeonenko93

2023-08-19 03:55 UTC, z8q requested changes

2023-08-19 03:55 UTC, z8q commented on ewm-stats-service/stats_client/src/main/java/ru/practicum/StatClient.java
> +    //TODO сделать внебрение базового урл через переменные окружения докер компоуз
todo до завершения диплома лучше все закрыть)

2023-08-21 07:19 UTC, DenisLeonenko93 commented on ewm-main-service/main_server/src/main/java/ru/practicum/event/controller/EventAdminController.java
> +    //TODO попробовать анотацию DateTimeFormat в параметрах запроса rangeStart
Странные эти TODO, вроде полезно, но все равно про них забываешь) Надо сделать TODO для проверки TODO

2023-08-21 07:50 UTC, DenisLeonenko93 commented on ewm-main-service/main_server/src/main/java/ru/practicum/category/model/Category.java
> +    public int hashCode() {
Убрал у всех сущностей переопределение equals() and hashCode(), т.к. у нас нет сравнений сущностей между собой в приложении.

2023-08-21 08:16 UTC, DenisLeonenko93 commented on ewm-main-service/main_server/src/main/java/ru/practicum/category/model/Category.java
> +    public int hashCode() {
Точнее оставил equals() and hashCode() с одним полем id  для Event, т.к. будет использоваться Set<Event>. Я ведь правильно понял?

2023-08-21 08:19 UTC, DenisLeonenko93 commented on ewm-main-service/main_server/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @ManyToMany
Увидел дополнительный запрос в методе getAll в CompilationServiceImpl. Попытался исправить через JOIN FETCH в @Query, но почему-то возвращает пустой лист. Указал EAGER для загрузки листа ивентов.

2023-08-21 08:30 UTC, DenisLeonenko93 commented on ewm-main-service/main_server/src/main/java/ru/practicum/event/mapper/EventMapper.java
> +            expression = "java(categoryFromDto(categoryService.getCategory(eventNewDto.getCategory())))")
Спасибо, я не нашел такого решения, Смотрел на эту строку и ужасался.

2023-08-21 18:31 UTC, z8q approved these changes

2023-08-21 19:31 UTC, merged