Feature rating events
DenisLeonenko93/java-explore-with-me pull request #5
Opened 2023-08-24 10:31 UTC by DenisLeonenko93

2023-08-24 21:03 UTC, z8q requested changes

2023-08-24 21:03 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/rating/controller/RatingPrivateController.java
> +@Validated
Обычно Validated добавляем, когда есть аннотации валидации на аргументах (`@Max`, `@Min` и др.). Тут не вижу такого

2023-08-24 21:03 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/event/model/dto/EventFullDto.java
> +    long likes;
почему для полей лонг выше использовались обертки Long, а тут примитивы?

2023-08-24 21:03 UTC, z8q commented on README.md
>  # java-explore-with-me
Checks по какой-то причине не сработали. Нужно подключить

2023-08-25 05:12 UTC, DenisLeonenko93 commented on ewm-main-service/src/main/java/ru/practicum/event/model/dto/EventFullDto.java
> +    long likes;
Конкретно здесь указал для того, чтоб при инициализации был 0, а не null. Возможно было бы лучше изменить выше, но не хочется ломать что уже работает, мало ли чего)

2023-08-26 02:48 UTC, z8q approved these changes

2023-08-26 05:51 UTC, merged